version: '3.4'

services:
  db:
    container_name: db
    image: mysql
    env_file: .env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      # - /C/Users/USER/Desktop/oasip-kp1/datadir:/var/lib/mysql
      # - /C/Users/USER/Desktop/oasip-kp1/db/:/docker-entrypoint-initdb.d
      - /D/integrated/OASIP-KP-1/datadir:/var/lib/mysql
      - /D/integrated/OASIP-KP-1/db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    restart: on-failure

  back:
    container_name: back
    # image: ghcr.io/int221-integrated-project-kp1/oasip-api:latest
    image: back
    env_file: .env
    build: ./back-end
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "$MYSQLDB_USER",
              "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
        }'
  front:
    container_name: front
    image: front
    env_file: .env
    depends_on:
      - back
    build: ./front-end
    ports:
      - $FRONT_LOCAL_PORT:$FRONT_DOCKER_PORT
    links:
      - back



