version: '3.4'

services:
  db:
    container_name: db
    image: mysql
    ports:
      - 3360:3306
    volumes:
      - /C/Users/USER/Desktop/datadir:/var/lib/mysql0
      - /C/Users/USER/Desktop/oasip-kp1/db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    restart: on-failure

  back:
    container_name: back
    # image: ghcr.io/int221-integrated-project-kp1/oasip-api:latest
    image: back
    build: ./back-end
    ports:
      - 3000:8080
    restart: on-failure
    depends_on:
      - db
    environment:
      # - DB_HOSTNAME= "db"
      # - spring.datasource.url= "jdbc:mysql://db:3306/mydb"


  