version: '3.4'

services:

  proxy:
    container_name: proxy
    image: nginx
    restart: always
    depends_on:
      - front
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  db:
    container_name: db
    image: mysql
    env_file: .env
    volumes:
      - ./datadir:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    restart: on-failure


  back:
    container_name: back
    image: ghcr.io/int221-integrated-project-kp1/back
    env_file: .env
    build: ./back-end
    restart: on-failure
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "$MYSQLDB_USER",
              "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
        }'
        
  front:
    container_name: front
    image: ghcr.io/int221-integrated-project-kp1/front
    env_file: .env
    depends_on:
      - back
    build: ./front-end
  



