# DISCORD NOTIFY STATE
  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        censor_username: false
        hide_links: false